language: c

git:
  depth: 3

matrix:
  include:
    # subsequent matrix options use these first settings
    - os: linux
      compiler: gcc
      env: WEXTRAFLAGS=-Werror
    - env: MULTI=1 WEXTRAFLAGS=-Werror
    # libtom has some warnings, so no WEXTRAFLAGS
    - env: BUNDLEDLIBTOM=--enable-bundled-libtom WEXTRAFLAGS=""
    - env: NOWRITEV=1 WEXTRAFLAGS=-Werror
    # libtomcrypt 1.18.1 fixes clang problems, distro doesn't have that yet
    - os: linux
      compiler: clang
      env: BUNDLEDLIBTOM=--enable-bundled-libtom WEXTRAFLAGS=""
    - os: osx
      compiler: clang
      env: WEXTRAFLAGS=""

# container-based builds
sudo: false
addons:
  apt:
    packages:
    # packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    - zlib1g-dev
    - libtomcrypt-dev
    - libtommath-dev


before_install:
  - if [ "$CC" = "clang" ]; then WEXTRAFLAGS="$WEXTRAFLAGS -Wno-error=incompatible-library-redeclaration" ; fi  # workaround

script:
  - autoconf && autoheader && ./configure "$BUNDLEDLIBTOM" CFLAGS="-O2 -Wall -Wno-pointer-sign $WEXTRAFLAGS" --prefix="$HOME/inst"
  - if [ "$NOWRITEV" = "1" ]; then sed -i -e s/HAVE_WRITEV/DONT_HAVE_WRITEV/ config.h ; fi
  - make -j3 
  # avoid concurrent install, osx/freebsd is racey (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208093)
  - make install 

after_success:
  - ~/inst/bin/dropbearkey -t rsa -f testrsa
  - ~/inst/bin/dropbearkey -t dss -f testdss
  - ~/inst/bin/dropbearkey -t ecdsa -f testec256 -s 256
  - ~/inst/bin/dropbearkey -t ecdsa -f testec384 -s 384
  - ~/inst/bin/dropbearkey -t ecdsa -f testec521 -s 521

branches:
  only:
    - master
    - coverity

